{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a5191ed-dcce-483f-b35c-9f6fdd0ea5db",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import yfinance as yf\n",
    "import time\n",
    "import requests\n",
    "\n",
    "# --- Page Config ---\n",
    "st.set_page_config(page_title=\"3-Day High Monitor\", page_icon=\"📊\")\n",
    "st.title(\"📉 3-Day High Pullback Monitor\")\n",
    "\n",
    "# --- Sidebar Configuration ---\n",
    "st.sidebar.header(\"Alert Settings\")\n",
    "bot_token = st.sidebar.text_input(\"Telegram Bot Token\", type=\"password\")\n",
    "chat_id = st.sidebar.text_input(\"Telegram Chat ID\")\n",
    "ticker_symbol = st.sidebar.text_input(\"Stock Ticker\", value=\"AAPL\").upper()\n",
    "drop_threshold = st.sidebar.slider(\"Alert Threshold (%)\", 1, 20, 5)\n",
    "\n",
    "# --- State Management ---\n",
    "if 'running' not in st.session_state:\n",
    "    st.session_state.running = False\n",
    "\n",
    "def send_telegram(msg):\n",
    "    if bot_token and chat_id:\n",
    "        url = f\"https://api.telegram.org/bot{bot_token}/sendMessage\"\n",
    "        payload = {\"chat_id\": chat_id, \"text\": msg}\n",
    "        try:\n",
    "            requests.post(url, json=payload)\n",
    "        except Exception as e:\n",
    "            st.error(f\"Telegram Error: {e}\")\n",
    "\n",
    "# --- Control Buttons ---\n",
    "col1, col2 = st.columns(2)\n",
    "if col1.button(\"▶️ Start Monitoring\", use_container_width=True):\n",
    "    st.session_state.running = True\n",
    "if col2.button(\"🛑 Stop Monitoring\", use_container_width=True):\n",
    "    st.session_state.running = False\n",
    "\n",
    "# --- Main Logic ---\n",
    "if st.session_state.running:\n",
    "    status_box = st.empty()\n",
    "    metric_container = st.empty()\n",
    "    \n",
    "    while st.session_state.running:\n",
    "        try:\n",
    "            ticker = yf.Ticker(ticker_symbol)\n",
    "            \n",
    "            # 1. Fetch 3 days of data to find the 3-day high\n",
    "            # We use 1h interval for the 3-day high to be efficient\n",
    "            hist_3d = ticker.history(period='3d', interval='1h')\n",
    "            # 2. Fetch 1 day of 1m data for the most accurate current price\n",
    "            hist_today = ticker.history(period='1d', interval='1m')\n",
    "            \n",
    "            if not hist_3d.empty and not hist_today.empty:\n",
    "                current_price = hist_today['Close'].iloc[-1]\n",
    "                # Calculate the max high over the last 3 trading days\n",
    "                three_day_high = hist_3d['High'].max()\n",
    "                \n",
    "                # Calculate percentage drop from that 3-day peak\n",
    "                percent_drop = ((current_price - three_day_high) / three_day_high) * 100\n",
    "                \n",
    "                # Update Dashboard\n",
    "                with metric_container.container():\n",
    "                    m1, m2, m3 = st.columns(3)\n",
    "                    m1.metric(\"Current Price\", f\"${current_price:.2f}\")\n",
    "                    m2.metric(\"3-Day High\", f\"${three_day_high:.2f}\")\n",
    "                    m3.metric(\"vs 3-Day High\", f\"{percent_drop:.2f}%\", delta_color=\"inverse\")\n",
    "\n",
    "                # Trigger Alert\n",
    "                if percent_drop <= -drop_threshold:\n",
    "                    msg = (f\"⚠️ {ticker_symbol} Alert!\\n\"\n",
    "                           f\"Current: ${current_price:.2f}\\n\"\n",
    "                           f\"3-Day High: ${three_day_high:.2f}\\n\"\n",
    "                           f\"Drop: {abs(percent_drop):.2f}%\")\n",
    "                    send_telegram(msg)\n",
    "                    st.warning(\"Alert sent to Telegram!\")\n",
    "                    time.sleep(600) # 10-minute cooldown after alert\n",
    "\n",
    "            status_box.text(f\"Last updated: {time.strftime('%H:%M:%S')}\")\n",
    "            time.sleep(120) # Wait 2 minutes\n",
    "            st.rerun()\n",
    "\n",
    "        except Exception as e:\n",
    "            st.error(f\"Error fetching data: {e}\")\n",
    "            st.session_state.running = False\n",
    "            break"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
